# Generated by Django 5.0.4 on 2024-06-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='заблокирован'),
        ),
    ]
