# Generated by Django 5.0.3 on 2024-04-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_mailingstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='название'),
        ),
    ]
