# Generated by Django 5.0.3 on 2024-04-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_mailing_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='name',
            field=models.CharField(default='tests', max_length=50, verbose_name='название'),
        ),
    ]
