# Generated by Django 5.0.3 on 2024-04-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_mailing_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailingStatus',
            new_name='MailingLog',
        ),
    ]
