# Generated by Django 5.0.4 on 2024-06-04 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0012_client_owner_message_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('set_activation_mailing', 'Can deactivate a mailing')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
